# Generated by Django 4.1 on 2025-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="qr_code_count",
            field=models.PositiveIntegerField(default=500),
        ),
    ]
