# Generated by Django 5.1.6 on 2025-02-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0002_event_qr_code_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="qrmask/"),
        ),
    ]
