# Generated by Django 5.1.6 on 2025-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0003_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="qrmask/"),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="event_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
